### ISSUE TITLE
Does not build with rust 1.80.0

### ISSUE THREAD

**Issue by jaredmontoya** [Aloxaf/silicon#255]
```shell
error[E0282]: type annotations needed for `Box<_>`
  --> /build/cargo-vendor-dir/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by jaredmontoya** [comment]
https://github.com/NixOS/nixpkgs/issues/332957

**Comment by jaredmontoya** [comment]
Will be fixed by https://github.com/Aloxaf/silicon/pull/254 I guess

**Comment by jaredmontoya** [comment]
@Aloxaf sorry for the ping, this project does not look very active and I am not sure how long it will take for one of those pull requests to be reviewed without any notifications.
